### ISSUE TITLE
HostPortWaitStrategy is insufficient as a liveness check for SQL Server containers 

### ISSUE THREAD

**Issue by annirudh** [testcontainers/testcontainers-java-module-mssqlserver#12]
The `MSSQLServerContainer` implementation overrides the implementation of `waitUntilContainerStarted()` as supplied by `JdbcDatabaseContainer` with an implementation that uses the `HostPortWaitStrategy`:

```
    @Override
    protected void waitUntilContainerStarted() {
        getWaitStrategy().waitUntilReady(this);
    }
```

Consequently, the container transitions to the started state as soon as the SQL Server instance within the container accepts a single TCP connection. However, there is a window of time between when SQL Server starts listening to incoming TCP connections and when SQL Server is actually ready to accept incoming JDBC connection requests. SQL Server will reject all JDBC connections that occur within that window (notice that SQL Server simply returns an EOF here):

```
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'SA'. ClientConnectionId:b58f301a-c6aa-42fc-88a4-308ae272bf43
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:232)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:291)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:111)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:4376)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:3188)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$100(SQLServerConnection.java:61)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:3151)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7535)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2438)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:1973)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1616)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1447)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:788)
	at com.microsoft.sqlserver.jdbc.SQLServerDataSource.getConnectionInternal(SQLServerDataSource.java:719)
	at com.microsoft.sqlserver.jdbc.SQLServerDataSource.getConnection(SQLServerDataSource.java:71)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
	... 58 more
```

Once the container has been up for a few seconds, however, the JDBC connections succeed.

I believe that the fix is to rely on the default implementation of `waitUntilContainerStarted()` as supplied by `JdbcDatabaseContainer` as it waits for a successful JDBC connection before marking the container as running.

I am happy to provide a diff with the above change if you agree that this is the correct fix. An important note is that this change would also increase the liveness timeout window to 2 minutes (as specified by `JdbcDatabaseContainer.waitUntilContainerStarted()`).

**Comment by annirudh** [comment]
Apologies, I was using an earlier version and noticed that commit `86f332691bb3f9745cd7bfe0e143c916f02ddd0c` which is included in version 1.5.1 fixes the issue.
